#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

{
  cat <<'HEADER'
# NOTICE

Third-party libraries and their licenses used by Hooty.

Generated by: `scripts/update_notice.sh`

HEADER
  uv run pip-licenses --format=markdown --order=license --with-urls \
    | grep -v '^| *|' \
    | grep -v '^| hooty '

  # Non-pip dependencies (data-only references, etc.)
  echo '| litellm (data only)       | —           | MIT License                                                                    | https://github.com/BerriAI/litellm                                                |'
} > NOTICE.md

echo "Updated NOTICE.md"
